// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
void ui_event_BootScreen(lv_event_t * e);
lv_obj_t * ui_BootScreen;
lv_obj_t * ui_lblBootScreenAppTitle;
lv_obj_t * ui_lblBootScreenGitUrl;
lv_obj_t * ui_lblBootScreenAppVer;

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_panelMainScreenHeader;
lv_obj_t * ui_panelMainScreenHeaderLeft;
lv_obj_t * ui_imgMainScreenHeaderTimer;
lv_obj_t * ui_imgMainScreenHeaderClock;
lv_obj_t * ui_lblMainScreenHeaderTimerText;
lv_obj_t * ui_panelMainScreenHeaderDivider;
lv_obj_t * ui_panelMainScreenHeaderRight;
lv_obj_t * ui_imgMainScreenHeaderLockStatus;
lv_obj_t * ui_imgMainScreenHeaderWifi;
lv_obj_t * ui_panelMainScreenMid;
lv_obj_t * ui_lblDeskHeightValue;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_imgMainScreenDeskHeightDirUp;
lv_obj_t * ui_imgMainScreenDeskHeightDirDown;
lv_obj_t * ui_imgMainScreenDeskHeightDirNone;
lv_obj_t * ui_lblDeskHeightUnits;
lv_obj_t * ui_panelMainScreenFooter;
lv_obj_t * ui_lblMainScreenFooterNotifText;

// SCREEN: ui_MenuScreen
void ui_MenuScreen_screen_init(void);
void ui_event_MenuScreen(lv_event_t * e);
lv_obj_t * ui_MenuScreen;
lv_obj_t * ui_panelMenuScreenHeader;
lv_obj_t * ui_Label1;
void ui_event_rollerMenuScreenItems(lv_event_t * e);
lv_obj_t * ui_rollerMenuScreenItems;

// SCREEN: ui_MemoryScreen
void ui_MemoryScreen_screen_init(void);
void ui_event_MemoryScreen(lv_event_t * e);
lv_obj_t * ui_MemoryScreen;
lv_obj_t * ui_panelMemoryScreenHeader;
lv_obj_t * ui_Label2;
void ui_event_rollerMemoryScreenItems(lv_event_t * e);
lv_obj_t * ui_rollerMemoryScreenItems;

// SCREEN: ui_TimerScreen
void ui_TimerScreen_screen_init(void);
void ui_event_TimerScreen(lv_event_t * e);
lv_obj_t * ui_TimerScreen;
lv_obj_t * ui_panelTimerScreenHeader;
lv_obj_t * ui_Label3;
void ui_event_rollerTimerScreenItems(lv_event_t * e);
lv_obj_t * ui_rollerTimerScreenItems;

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
void ui_event_SettingsScreen(lv_event_t * e);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_panelSettingsScreenHeader;
lv_obj_t * ui_Label4;
void ui_event_rollerSettingsScreenItems(lv_event_t * e);
lv_obj_t * ui_rollerSettingsScreenItems;
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_empty_x[1] = {&ui_img_empty_12x12_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 1
    #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BootScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 100, 1000);
    }
}
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(ui_MenuScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        mainScreenLoadStart(e);
    }
}
void ui_event_MenuScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        menuScreenLoadStart(e);
    }
}
void ui_event_rollerMenuScreenItems(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        menuScreenRollerItemClicked(e);
    }
}
void ui_event_MemoryScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        memoryScreenLoadStart(e);
    }
}
void ui_event_rollerMemoryScreenItems(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        memoryScreenRollerItemClicked(e);
    }
}
void ui_event_TimerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        timerScreenLoadStart(e);
    }
}
void ui_event_rollerTimerScreenItems(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        timerScreenRollerItemClicked(e);
    }
}
void ui_event_SettingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        settingsScreenLoadStart(e);
    }
}
void ui_event_rollerSettingsScreenItems(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        settingsScreenRollerItemClicked(e);
    }
}
void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        initialActions(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
lv_theme_t * theme = lv_theme_mono_init(dispp, false, LV_FONT_DEFAULT);

    lv_disp_set_theme(dispp, theme);
    ui_BootScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_MenuScreen_screen_init();
    ui_MemoryScreen_screen_init();
    ui_TimerScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_BootScreen);
}
