// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
void ui_event_BootScreen(lv_event_t * e);
lv_obj_t * ui_BootScreen;
lv_obj_t * ui_lblBootScreenAppTitle;
lv_obj_t * ui_lblBootScreenGitUrl;
lv_obj_t * ui_lblBootScreenAppVer;

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_panelMainScreenHeader;
lv_obj_t * ui_panelMainScreenHeaderLeft;
lv_obj_t * ui_imgMainScreenHeaderTimer;
lv_obj_t * ui_lblMainScreenHeaderTimerText;
lv_obj_t * ui_panelMainScreenHeaderDivider;
lv_obj_t * ui_panelMainScreenHeaderRight;
lv_obj_t * ui_imgMainScreenHeaderLockStatus;
lv_obj_t * ui_imgMainScreenHeaderWifi;
lv_obj_t * ui_panelMainScreenMid;
lv_obj_t * ui_lblDeskHeightValue;
lv_obj_t * ui_lblDeskHeightUnits;
lv_obj_t * ui_panelMainScreenFooter;
lv_obj_t * ui_lblMainScreenFooterNotifText;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 1
    #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BootScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 100, 1000);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_mono_init(dispp, false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_BootScreen_screen_init();
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_BootScreen);
}
