// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "ui.h"
#include "esp_log.h"

lv_group_t * ui_MainScreen_group;
lv_group_t * ui_MenuScreen_group;
lv_indev_t* indev_encoder;


void initialActions(lv_event_t * e)
{
    ui_MainScreen_group = lv_group_create();
    lv_group_add_obj(ui_MainScreen_group, ui_MainScreen);

    ui_MenuScreen_group = lv_group_create();
    lv_group_add_obj(ui_MenuScreen_group, ui_rollerMenuScreenItems);

}

void mainScreenLoadStart(lv_event_t * e)
{
    lv_indev_set_group(indev_encoder, ui_MainScreen_group);
}



void menuScreenLoadStart(lv_event_t * e) {
   // lv_group_set_editing(ui_MenuScreen_group,true);
    lv_indev_set_group(indev_encoder, ui_MenuScreen_group);

}

void menuScreenRollerItemClicked(lv_event_t * e)
{
    switch (lv_roller_get_selected(ui_rollerMenuScreenItems)) {
        case 0:
            _ui_screen_change(ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
            break;
        case 1:
            _ui_screen_change(ui_MemoryScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
            break;
        case 2:
            _ui_screen_change(ui_TimerScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
            break;
        case 3:
            _ui_screen_change(ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
            break;
    }
}