// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "../ui.h"

void ui_MemoryScreen_screen_init(void)
{
    ui_MemoryScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MemoryScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_MemoryScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_flex_flow(ui_MemoryScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MemoryScreen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_panelMemoryScreenHeader = lv_obj_create(ui_MemoryScreen);
    lv_obj_set_width(ui_panelMemoryScreenHeader, 128);
    lv_obj_set_height(ui_panelMemoryScreenHeader, 13);
    lv_obj_set_align(ui_panelMemoryScreenHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelMemoryScreenHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelMemoryScreenHeader, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_state(ui_panelMemoryScreenHeader, LV_STATE_DISABLED);       /// States
    lv_obj_clear_flag(ui_panelMemoryScreenHeader,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_panelMemoryScreenHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelMemoryScreenHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelMemoryScreenHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelMemoryScreenHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panelMemoryScreenHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_panelMemoryScreenHeader);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "MEMORY");
    lv_obj_clear_flag(ui_Label2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label2, &ui_font_MontserratSemiBold10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerMemoryScreenItems = lv_roller_create(ui_MemoryScreen);
    lv_roller_set_options(ui_rollerMemoryScreenItems, "M1\nM2\nM3\nBACK", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerMemoryScreenItems, 128);
    lv_obj_set_height(ui_rollerMemoryScreenItems, 49);
    lv_obj_set_align(ui_rollerMemoryScreenItems, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rollerMemoryScreenItems,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_rollerMemoryScreenItems, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMemoryScreenItems, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerMemoryScreenItems, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMemoryScreenItems, &ui_font_MontserratSemiBold10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMemoryScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMemoryScreenItems, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMemoryScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerMemoryScreenItems, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerMemoryScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerMemoryScreenItems, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerMemoryScreenItems, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMemoryScreenItems, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerMemoryScreenItems, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMemoryScreenItems, &ui_font_MontserratSemiBold14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMemoryScreenItems, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMemoryScreenItems, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rollerMemoryScreenItems, ui_event_rollerMemoryScreenItems, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MemoryScreen, ui_event_MemoryScreen, LV_EVENT_ALL, NULL);

}
