// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_MainScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_flex_flow(ui_MainScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MainScreen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_panelMainScreenHeader = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_panelMainScreenHeader, 128);
    lv_obj_set_height(ui_panelMainScreenHeader, 13);
    lv_obj_set_x(ui_panelMainScreenHeader, 0);
    lv_obj_set_y(ui_panelMainScreenHeader, -21);
    lv_obj_set_align(ui_panelMainScreenHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelMainScreenHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelMainScreenHeader, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelMainScreenHeader,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_panelMainScreenHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelMainScreenHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelMainScreenHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelMainScreenHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panelMainScreenHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelMainScreenHeaderLeft = lv_obj_create(ui_panelMainScreenHeader);
    lv_obj_set_width(ui_panelMainScreenHeaderLeft, 61);
    lv_obj_set_height(ui_panelMainScreenHeaderLeft, 12);
    lv_obj_set_align(ui_panelMainScreenHeaderLeft, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelMainScreenHeaderLeft,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_panelMainScreenHeaderLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelMainScreenHeaderLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelMainScreenHeaderLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panelMainScreenHeaderLeft, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainScreenHeaderTimer = lv_img_create(ui_panelMainScreenHeaderLeft);
    lv_img_set_src(ui_imgMainScreenHeaderTimer, &ui_img_stopwatch_png);
    lv_obj_set_width(ui_imgMainScreenHeaderTimer, 12);
    lv_obj_set_height(ui_imgMainScreenHeaderTimer, 12);
    lv_obj_set_x(ui_imgMainScreenHeaderTimer, -21);
    lv_obj_set_y(ui_imgMainScreenHeaderTimer, -1);
    lv_obj_set_align(ui_imgMainScreenHeaderTimer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainScreenHeaderTimer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_imgMainScreenHeaderTimer,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_imgMainScreenHeaderTimer, 240);

    ui_imgMainScreenHeaderClock = lv_img_create(ui_panelMainScreenHeaderLeft);
    lv_img_set_src(ui_imgMainScreenHeaderClock, &ui_img_clock_png);
    lv_obj_set_width(ui_imgMainScreenHeaderClock, 12);
    lv_obj_set_height(ui_imgMainScreenHeaderClock, 12);
    lv_obj_set_x(ui_imgMainScreenHeaderClock, -21);
    lv_obj_set_y(ui_imgMainScreenHeaderClock, -1);
    lv_obj_set_align(ui_imgMainScreenHeaderClock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgMainScreenHeaderClock,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_imgMainScreenHeaderClock, 230);
    lv_obj_set_style_border_side(ui_imgMainScreenHeaderClock, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMainScreenHeaderTimerText = lv_label_create(ui_panelMainScreenHeaderLeft);
    lv_obj_set_width(ui_lblMainScreenHeaderTimerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMainScreenHeaderTimerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMainScreenHeaderTimerText, 3);
    lv_obj_set_y(ui_lblMainScreenHeaderTimerText, -1);
    lv_obj_set_align(ui_lblMainScreenHeaderTimerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMainScreenHeaderTimerText, "10:00");
    lv_obj_clear_flag(ui_lblMainScreenHeaderTimerText,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_lblMainScreenHeaderTimerText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelMainScreenHeaderDivider = lv_obj_create(ui_panelMainScreenHeader);
    lv_obj_set_width(ui_panelMainScreenHeaderDivider, 38);
    lv_obj_set_height(ui_panelMainScreenHeaderDivider, 16);
    lv_obj_set_align(ui_panelMainScreenHeaderDivider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelMainScreenHeaderDivider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelMainScreenHeaderDivider, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelMainScreenHeaderDivider,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_panelMainScreenHeaderDivider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelMainScreenHeaderDivider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelMainScreenHeaderDivider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panelMainScreenHeaderDivider, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelMainScreenHeaderRight = lv_obj_create(ui_panelMainScreenHeader);
    lv_obj_set_width(ui_panelMainScreenHeaderRight, 43);
    lv_obj_set_height(ui_panelMainScreenHeaderRight, 16);
    lv_obj_set_align(ui_panelMainScreenHeaderRight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelMainScreenHeaderRight,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_panelMainScreenHeaderRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelMainScreenHeaderRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelMainScreenHeaderRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panelMainScreenHeaderRight, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainScreenHeaderLockStatus = lv_img_create(ui_panelMainScreenHeaderRight);
    lv_img_set_src(ui_imgMainScreenHeaderLockStatus, &ui_img_wifi_solid_png);
    lv_obj_set_width(ui_imgMainScreenHeaderLockStatus, 12);
    lv_obj_set_height(ui_imgMainScreenHeaderLockStatus, 12);
    lv_obj_set_x(ui_imgMainScreenHeaderLockStatus, -3);
    lv_obj_set_y(ui_imgMainScreenHeaderLockStatus, -1);
    lv_obj_set_align(ui_imgMainScreenHeaderLockStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgMainScreenHeaderLockStatus,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_imgMainScreenHeaderWifi = lv_img_create(ui_panelMainScreenHeaderRight);
    lv_img_set_src(ui_imgMainScreenHeaderWifi, &ui_img_wifi_solid_png);
    lv_obj_set_width(ui_imgMainScreenHeaderWifi, 12);
    lv_obj_set_height(ui_imgMainScreenHeaderWifi, 12);
    lv_obj_set_x(ui_imgMainScreenHeaderWifi, 11);
    lv_obj_set_y(ui_imgMainScreenHeaderWifi, -1);
    lv_obj_set_align(ui_imgMainScreenHeaderWifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgMainScreenHeaderWifi,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_panelMainScreenMid = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_panelMainScreenMid, 128);
    lv_obj_set_height(ui_panelMainScreenMid, 40);
    lv_obj_set_x(ui_panelMainScreenMid, 0);
    lv_obj_set_y(ui_panelMainScreenMid, -21);
    lv_obj_set_align(ui_panelMainScreenMid, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelMainScreenMid, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelMainScreenMid, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_panelMainScreenMid,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_side(ui_panelMainScreenMid, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDeskHeightValue = lv_label_create(ui_panelMainScreenMid);
    lv_obj_set_width(ui_lblDeskHeightValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDeskHeightValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblDeskHeightValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDeskHeightValue, "128.5");
    lv_obj_clear_flag(ui_lblDeskHeightValue,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_lblDeskHeightValue, &ui_font_MontserratSemiBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_panelMainScreenMid);
    lv_obj_set_height(ui_Panel2, 30);
    lv_obj_set_width(ui_Panel2, lv_pct(30));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainScreenDeskHeightDirUp = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_imgMainScreenDeskHeightDirUp, &ui_img_sort_up_png);
    lv_obj_set_width(ui_imgMainScreenDeskHeightDirUp, 12);
    lv_obj_set_height(ui_imgMainScreenDeskHeightDirUp, 12);
    lv_obj_set_x(ui_imgMainScreenDeskHeightDirUp, 11);
    lv_obj_set_y(ui_imgMainScreenDeskHeightDirUp, -1);
    lv_obj_set_align(ui_imgMainScreenDeskHeightDirUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainScreenDeskHeightDirUp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_imgMainScreenDeskHeightDirUp,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_imgMainScreenDeskHeightDirDown = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_imgMainScreenDeskHeightDirDown, &ui_img_sort_down_png);
    lv_obj_set_width(ui_imgMainScreenDeskHeightDirDown, 12);
    lv_obj_set_height(ui_imgMainScreenDeskHeightDirDown, 12);
    lv_obj_set_x(ui_imgMainScreenDeskHeightDirDown, 11);
    lv_obj_set_y(ui_imgMainScreenDeskHeightDirDown, -1);
    lv_obj_set_align(ui_imgMainScreenDeskHeightDirDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainScreenDeskHeightDirDown, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_imgMainScreenDeskHeightDirDown,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_imgMainScreenDeskHeightDirNone = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_imgMainScreenDeskHeightDirNone, &ui_img_empty_12x12_png);
    lv_obj_set_width(ui_imgMainScreenDeskHeightDirNone, 12);
    lv_obj_set_height(ui_imgMainScreenDeskHeightDirNone, 12);
    lv_obj_set_x(ui_imgMainScreenDeskHeightDirNone, 11);
    lv_obj_set_y(ui_imgMainScreenDeskHeightDirNone, -1);
    lv_obj_set_align(ui_imgMainScreenDeskHeightDirNone, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_imgMainScreenDeskHeightDirNone,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_lblDeskHeightUnits = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lblDeskHeightUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDeskHeightUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDeskHeightUnits, 45);
    lv_obj_set_y(ui_lblDeskHeightUnits, 0);
    lv_obj_set_align(ui_lblDeskHeightUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDeskHeightUnits, "cm");
    lv_obj_clear_flag(ui_lblDeskHeightUnits,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_lblDeskHeightUnits, &ui_font_MontserratSemiBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lblDeskHeightUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lblDeskHeightUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lblDeskHeightUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lblDeskHeightUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelMainScreenFooter = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_panelMainScreenFooter, 128);
    lv_obj_set_height(ui_panelMainScreenFooter, 12);
    lv_obj_set_x(ui_panelMainScreenFooter, 0);
    lv_obj_set_y(ui_panelMainScreenFooter, -21);
    lv_obj_set_align(ui_panelMainScreenFooter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelMainScreenFooter,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_panelMainScreenFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelMainScreenFooter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelMainScreenFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelMainScreenFooter, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panelMainScreenFooter, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMainScreenFooterNotifText = lv_label_create(ui_panelMainScreenFooter);
    lv_obj_set_width(ui_lblMainScreenFooterNotifText, 128);
    lv_obj_set_height(ui_lblMainScreenFooterNotifText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMainScreenFooterNotifText, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblMainScreenFooterNotifText, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lblMainScreenFooterNotifText, "This is a scrolling notification.");
    lv_obj_clear_flag(ui_lblMainScreenFooterNotifText,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_lblMainScreenFooterNotifText, &ui_font_MontserratSemiBold10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
