// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_SettingsScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_flex_flow(ui_SettingsScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsScreen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_panelSettingsScreenHeader = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_panelSettingsScreenHeader, 128);
    lv_obj_set_height(ui_panelSettingsScreenHeader, 13);
    lv_obj_set_align(ui_panelSettingsScreenHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_panelSettingsScreenHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_panelSettingsScreenHeader, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_state(ui_panelSettingsScreenHeader, LV_STATE_DISABLED);       /// States
    lv_obj_clear_flag(ui_panelSettingsScreenHeader,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_panelSettingsScreenHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelSettingsScreenHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelSettingsScreenHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelSettingsScreenHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_panelSettingsScreenHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_panelSettingsScreenHeader);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -1);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SETTINGS");
    lv_obj_clear_flag(ui_Label4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label4, &ui_font_MontserratSemiBold10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerSettingsScreenItems = lv_roller_create(ui_SettingsScreen);
    lv_roller_set_options(ui_rollerSettingsScreenItems, "WIFI\nMOTOR SPEED", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerSettingsScreenItems, 128);
    lv_obj_set_height(ui_rollerSettingsScreenItems, 49);
    lv_obj_set_align(ui_rollerSettingsScreenItems, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_rollerSettingsScreenItems, LV_STATE_CHECKED | LV_STATE_PRESSED | LV_STATE_FOCUSED);       /// States
    lv_obj_clear_flag(ui_rollerSettingsScreenItems,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_rollerSettingsScreenItems, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerSettingsScreenItems, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerSettingsScreenItems, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerSettingsScreenItems, &ui_font_MontserratSemiBold10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerSettingsScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerSettingsScreenItems, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerSettingsScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerSettingsScreenItems, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerSettingsScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerSettingsScreenItems, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerSettingsScreenItems, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerSettingsScreenItems, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerSettingsScreenItems, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerSettingsScreenItems, &ui_font_MontserratSemiBold14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerSettingsScreenItems, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerSettingsScreenItems, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

}
