// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "../ui.h"

void ui_testMenuScreen_screen_init(void)
{
    ui_testMenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_testMenuScreen,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_testMenuScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_flex_flow(ui_testMenuScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_testMenuScreen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_rollerMenuScreenItems1 = lv_roller_create(ui_testMenuScreen);
    lv_roller_set_options(ui_rollerMenuScreenItems1, "<    BACK       \nMEMORY\nTIMER\nSETTINGS", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerMenuScreenItems1, lv_pct(100));
    lv_obj_set_height(ui_rollerMenuScreenItems1, lv_pct(100));
    lv_obj_set_align(ui_rollerMenuScreenItems1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_rollerMenuScreenItems1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_rollerMenuScreenItems1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_rollerMenuScreenItems1,
                      LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_rollerMenuScreenItems1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMenuScreenItems1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerMenuScreenItems1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMenuScreenItems1, &ui_font_MontserratSemiBold10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMenuScreenItems1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMenuScreenItems1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMenuScreenItems1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rollerMenuScreenItems1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rollerMenuScreenItems1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerMenuScreenItems1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerMenuScreenItems1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerMenuScreenItems1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMenuScreenItems1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerMenuScreenItems1, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMenuScreenItems1, &ui_font_MontserratSemiBold14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMenuScreenItems1, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMenuScreenItems1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rollerMenuScreenItems1, ui_event_rollerMenuScreenItems1, LV_EVENT_ALL, NULL);

}
