// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ElectricDeskControllerUI

#include "../ui.h"

void ui_TestRollerScreen_screen_init(void)
{
    ui_TestRollerScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TestRollerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_TestRollerScreen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TestRollerScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_rollerTestRollerScreenItems = lv_roller_create(ui_TestRollerScreen);
    lv_roller_set_options(ui_rollerTestRollerScreenItems, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerTestRollerScreenItems, 128);
    lv_obj_set_height(ui_rollerTestRollerScreenItems, 64);
    lv_obj_set_align(ui_rollerTestRollerScreenItems, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_rollerTestRollerScreenItems, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerTestRollerScreenItems, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerTestRollerScreenItems, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerTestRollerScreenItems, &ui_font_MontserratSemiBold10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerTestRollerScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerTestRollerScreenItems, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerTestRollerScreenItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerTestRollerScreenItems, lv_color_hex(0xFFFFFF),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerTestRollerScreenItems, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerTestRollerScreenItems, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerTestRollerScreenItems, &ui_font_MontserratSemiBold14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerTestRollerScreenItems, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerTestRollerScreenItems, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerTestRollerScreenItems, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

}
